#!/usr/bin/env bash

echo -n "enter the first number:"; read x
echo -n "enter the second number:"; read y
if [[ "$x" -lt "$y" ]]; then
        echo "$x < $y"
elif [[ "$x" -gt "$y" ]]; then
        echo "$x > $y"
else
        echo "$x == $y"
fi
